####数据库配置信息#######
datasource:
    url: jdbc:mysql://localhost:3306/spadmin?&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    
    
####系统参数配置######
system:
	path:
		web: /
		admin: /admin
		common: /common
		js: /admin/js
		css: /admin/css
		image: /admin/image
		upload: /upload